### ISSUE TITLE
Its not obvious that you can click on the avatars 

### ISSUE THREAD

**Issue by felipesere** [felipesere/advisorex#81]
It looks like the labels/names are clickable (which they aren't) and the image isn't (which it should).

Probably add something like this:

```css
.avatar:hover {
  cursor: pointer;
}
```
